name: Flask App CI/CD Pipeline

on: 
  workflow_dispatch:
  push:
    paths:
      - flask-app/**
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
  GITHUB_BRANCH: ${{ github.ref_name }}
  REGISTRY: hub.k8s.ucar.edu
  PROJECT: gitops-workshop
  USERNAME: slevis-lmwg

jobs:
  image-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d.%H.%M')" >> $GITHUB_OUTPUT
        
      - name: Registry login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HARBOR_ROBOT_NAME }}
          password: ${{ secrets.HARBOR_ROBOT_PW }}
          
      - name: Build container image
        run: |
          docker buildx build -t ${{ env.REGISTRY }}/${{ env.PROJECT }}/flask-demo-${{ env.USERNAME }}:${{ steps.date.outputs.date }} .
          
      - name: Push container image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.PROJECT }}/flask-demo-${{ env.USERNAME }}:${{ steps.date.outputs.date }}
          
      - name: Update Helm values.yaml
        run: |
          sed -i "s|image: .*|image: ${{ env.REGISTRY }}/${{ env.PROJECT }}/flask-demo-${{ env.USERNAME }}:${{ steps.date.outputs.date }}|" flask-helm/values.yaml
          
      - name: Update Helm Chart.yaml appVersion
        run: |
          sed -i "s|appVersion: .*|appVersion: ${{ steps.date.outputs.date }}|" flask-helm/Chart.yaml
          
      - name: Commit and push changes
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git add flask-helm/values.yaml flask-helm/Chart.yaml
          git commit -m "Update Helm chart with new image: ${{ steps.date.outputs.date }}"
          git push
